# Generated by Django 6.0.7 on 2026-07-21 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_map', '0032_alter_floorplantile_height_alter_floorplantile_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommarkertype',
            name='icon',
            field=models.CharField(default='mdi-shape', max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid MDI icon class (e.g. mdi-server-network).', regex='^mdi-[a-z0-9-]+$')]),
        ),
    ]
